version: "3.8"
services:
  member-service:
    build: .
    environment:
      - SECRET_KEY=very_secret_key
      - APP_PORT=3000
      - MESSAGE_BROKER_HOST="your_broker_host"
      - DB_HOST=your_db_host
      - DB_NAME=your_db_name
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password
    ports:
      - "3000:3000"
